# These are supported funding model platforms

# GitHub Sponsors username (replace with your username once approved)
github: [CYXWIZ-Lab]

# Patreon username
patreon: cyxwiz

# Other platforms (uncomment and fill in when ready)
# ko_fi: your_username
# open_collective: cyxmake
# liberapay: your_username
# buy_me_a_coffee: your_username

# Custom funding URLs
custom: ['https://www.patreon.com/posts/cyxwiz-projects-146571889']
