name: 'CyxMake Build'
description: 'AI-powered build automation with CyxMake'
author: 'CYXWIZ-Lab'
branding:
  icon: 'cpu'
  color: 'blue'

inputs:
  command:
    description: 'CyxMake command to run (build, analyze, clean)'
    required: false
    default: 'build'
  project-path:
    description: 'Path to project directory'
    required: false
    default: '.'
  build-type:
    description: 'Build type (Debug, Release, RelWithDebInfo, MinSizeRel)'
    required: false
    default: 'Release'
  parallel-jobs:
    description: 'Number of parallel build jobs (0 = auto)'
    required: false
    default: '0'
  ai-provider:
    description: 'AI provider to use (ollama, openai, anthropic, none)'
    required: false
    default: 'none'
  ai-api-key:
    description: 'API key for cloud AI provider'
    required: false
    default: ''
  dry-run:
    description: 'Run in dry-run mode (no changes made)'
    required: false
    default: 'false'
  auto-fix:
    description: 'Automatically fix build errors'
    required: false
    default: 'false'
  cyxmake-version:
    description: 'CyxMake version to use (latest, or specific version)'
    required: false
    default: 'latest'
  cache:
    description: 'Enable build caching'
    required: false
    default: 'true'

outputs:
  success:
    description: 'Whether the build succeeded'
    value: ${{ steps.build.outputs.success }}
  build-time:
    description: 'Total build time in seconds'
    value: ${{ steps.build.outputs.build_time }}
  errors-fixed:
    description: 'Number of errors automatically fixed'
    value: ${{ steps.build.outputs.errors_fixed }}
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup CyxMake
      id: setup
      shell: bash
      run: |
        echo "Setting up CyxMake..."

        # Determine OS
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          CYXMAKE_EXT=".exe"
          CYXMAKE_DIR="$LOCALAPPDATA/cyxmake"
        else
          CYXMAKE_EXT=""
          CYXMAKE_DIR="$HOME/.local/bin"
        fi

        mkdir -p "$CYXMAKE_DIR"

        # Download or build CyxMake
        if [[ "${{ inputs.cyxmake-version }}" == "latest" ]]; then
          VERSION="main"
        else
          VERSION="${{ inputs.cyxmake-version }}"
        fi

        echo "Installing CyxMake version: $VERSION"

        # Clone and build
        git clone --depth 1 --branch "$VERSION" https://github.com/CYXWIZ-Lab/cyxmake.git /tmp/cyxmake-src || true

        if [[ -d "/tmp/cyxmake-src" ]]; then
          cd /tmp/cyxmake-src
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCYXMAKE_BUILD_TESTS=OFF
          cmake --build . --config Release --parallel

          # Install binary
          if [[ -f "bin/cyxmake$CYXMAKE_EXT" ]]; then
            cp "bin/cyxmake$CYXMAKE_EXT" "$CYXMAKE_DIR/"
          elif [[ -f "Release/cyxmake$CYXMAKE_EXT" ]]; then
            cp "Release/cyxmake$CYXMAKE_EXT" "$CYXMAKE_DIR/"
          fi
        fi

        # Add to PATH
        echo "$CYXMAKE_DIR" >> $GITHUB_PATH
        echo "cyxmake_dir=$CYXMAKE_DIR" >> $GITHUB_OUTPUT

    - name: Cache CyxMake build artifacts
      id: cache
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.project-path }}/.cyxmake
          ${{ inputs.project-path }}/build
        key: cyxmake-${{ runner.os }}-${{ inputs.build-type }}-${{ hashFiles('**/CMakeLists.txt', '**/Cargo.toml', '**/package.json') }}
        restore-keys: |
          cyxmake-${{ runner.os }}-${{ inputs.build-type }}-
          cyxmake-${{ runner.os }}-

    - name: Generate CyxMake config
      shell: bash
      run: |
        cd "${{ inputs.project-path }}"

        cat > cyxmake.toml << 'CONFIGEOF'
        [ai]
        default_provider = "${{ inputs.ai-provider }}"
        timeout = 300
        max_tokens = 1024

        [ai.providers.openai]
        enabled = ${{ inputs.ai-provider == 'openai' }}
        type = "openai"
        api_key = "${{ inputs.ai-api-key }}"
        model = "gpt-4o-mini"

        [ai.providers.anthropic]
        enabled = ${{ inputs.ai-provider == 'anthropic' }}
        type = "anthropic"
        api_key = "${{ inputs.ai-api-key }}"
        model = "claude-3-haiku-20240307"

        [build]
        type = "${{ inputs.build-type }}"
        build_dir = "build"
        parallel_jobs = ${{ inputs.parallel-jobs }}

        [permissions]
        auto_approve_read = true
        auto_approve_build = true
        auto_approve_list = true
        always_confirm_delete = false
        always_confirm_install = ${{ inputs.auto-fix != 'true' }}
        always_confirm_command = false
        remember_choices = true

        [security]
        enable_dry_run = ${{ inputs.dry-run }}
        enable_audit = true

        [logging]
        level = "info"
        colors = false
        CONFIGEOF

        echo "Generated cyxmake.toml"

    - name: Run CyxMake
      id: build
      shell: bash
      run: |
        cd "${{ inputs.project-path }}"

        START_TIME=$(date +%s)
        ERRORS_FIXED=0
        SUCCESS="false"

        echo "Running CyxMake: ${{ inputs.command }}"

        case "${{ inputs.command }}" in
          build)
            if cyxmake build; then
              SUCCESS="true"
            fi
            ;;
          analyze)
            if cyxmake init; then
              SUCCESS="true"
            fi
            ;;
          clean)
            if cyxmake clean; then
              SUCCESS="true"
            fi
            ;;
          *)
            echo "Running custom command: ${{ inputs.command }}"
            if cyxmake "${{ inputs.command }}"; then
              SUCCESS="true"
            fi
            ;;
        esac

        END_TIME=$(date +%s)
        BUILD_TIME=$((END_TIME - START_TIME))

        echo "success=$SUCCESS" >> $GITHUB_OUTPUT
        echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT
        echo "errors_fixed=$ERRORS_FIXED" >> $GITHUB_OUTPUT

        if [[ "$SUCCESS" != "true" ]]; then
          echo "::error::CyxMake build failed"
          exit 1
        fi

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cyxmake-logs
        path: |
          ${{ inputs.project-path }}/.cyxmake/cyxmake.log
          ${{ inputs.project-path }}/.cyxmake/audit.log
        if-no-files-found: ignore
        retention-days: 7
